//! Namespace delegation for BPF privilege granting.
//!
//! This module implements the **"nsenter dance"** — the process by which the
//! daemon enters a target user namespace, mounts a
//! [bpffs](https://docs.kernel.org/bpf/bpf_token.html) with delegation
//! options, and returns to its original context.
//!
//! # Why is this needed?
//!
//! The bpffs superblock records `s_user_ns` at mount time. When a client
//! calls `BPF_TOKEN_CREATE`, the kernel checks that
//! `current_user_ns() == bpffs->s_user_ns`. A simple bind-mount from the
//! host namespace would set `s_user_ns` to `init_user_ns`, causing all
//! token creation attempts inside the target namespace to fail with `EPERM`.
//!
//! By entering the target namespace before mounting, `s_user_ns` is set to
//! the target's user namespace, and token creation works correctly.
//!
//! # Flow
//!
//! ```text
//! 1. Save current namespace FDs (user + mount)
//! 2. setns(target_userns, CLONE_NEWUSER)
//! 3. setns(target_mntns, CLONE_NEWNS)
//! 4. mount -t bpf bpf <path> -o delegate_cmds=...,delegate_progs=...
//! 5. setns(self_userns, CLONE_NEWUSER)   ← restore
//! 6. setns(self_mntns, CLONE_NEWNS)      ← restore
//! ```
//!
//! # Safety
//!
//! These functions temporarily change the calling thread's namespace context.
//! They must **not** be called concurrently with other namespace operations
//! on the same thread. In an async runtime, use a dedicated blocking thread.

use anyhow::{Context, Result};
use nix::mount::{mount, MsFlags};
use nix::sched::{setns, CloneFlags};
use std::fs::{File, OpenOptions};
use std::path::Path;

/// A target namespace to delegate BPF privileges to.
///
/// Created from a PID of any process running inside the target namespace.
/// The `userns_id` is the inode number of the user namespace and serves as
/// the key in the eBPF policy map.
#[derive(Debug)]
pub struct TargetNamespace {
    /// PID of a process in the target namespace (used to open
    /// `/proc/{pid}/ns/*`).
    pub pid: u32,
    /// User namespace inode ID (used as key in the policy eBPF map).
    pub userns_id: u64,
}

/// Mount options for bpffs that control which BPF operations are delegated.
///
/// Each field is a bitmap matching the kernel's `delegate_*` mount options
/// for bpffs. Set bits indicate allowed operations.
///
/// # Example
///
/// ```rust
/// use bpf_rbacd::namespace::DelegationOpts;
///
/// // Allow all operations (admin role)
/// let opts = DelegationOpts::allow_all();
///
/// // Allow specific operations from policy bitmaps
/// let opts = DelegationOpts::from_bitmaps(0x1F, 0x24, 0x06, 0x00);
/// ```
#[derive(Debug, Clone)]
pub struct DelegationOpts {
    /// Bitmap of allowed `bpf()` syscall commands.
    pub delegate_cmds: u32,
    /// Bitmap of allowed BPF program types.
    pub delegate_progs: u32,
    /// Bitmap of allowed BPF map types.
    pub delegate_maps: u32,
    /// Bitmap of allowed BPF attach types.
    pub delegate_attachs: u32,
}

impl DelegationOpts {
    /// Create delegation options that allow all operations (for admin roles).
    pub fn allow_all() -> Self {
        Self {
            delegate_cmds: 0xFFFFFFFF,
            delegate_progs: 0xFFFFFFFF,
            delegate_maps: 0xFFFFFFFF,
            delegate_attachs: 0xFFFFFFFF,
        }
    }

    /// Create delegation options from bitmaps generated by the policy engine.
    ///
    /// Use [`Policy::commands_bitmap`](crate::policy::Policy::commands_bitmap),
    /// [`Policy::prog_types_bitmap`](crate::policy::Policy::prog_types_bitmap),
    /// and [`Policy::map_types_bitmap`](crate::policy::Policy::map_types_bitmap)
    /// to compute these values.
    pub fn from_bitmaps(cmds: u32, progs: u32, maps: u32, attachs: u32) -> Self {
        Self {
            delegate_cmds: cmds,
            delegate_progs: progs,
            delegate_maps: maps,
            delegate_attachs: attachs,
        }
    }

    /// Format the delegation options as bpffs mount data.
    ///
    /// Returns a string like `delegate_cmds=0x1f,delegate_progs=0x24,...`
    /// suitable for passing to `mount(2)`.
    pub fn to_mount_data(&self) -> String {
        format!(
            "delegate_cmds={:#x},delegate_progs={:#x},delegate_maps={:#x},delegate_attachs={:#x}",
            self.delegate_cmds, self.delegate_progs, self.delegate_maps, self.delegate_attachs
        )
    }
}

impl TargetNamespace {
    /// Create from a PID, automatically resolving the user namespace inode ID.
    ///
    /// Reads `/proc/{pid}/ns/user` to obtain the inode number, which is used
    /// as the key in the eBPF policy map.
    ///
    /// # Errors
    ///
    /// Returns an error if the process does not exist or the namespace file
    /// cannot be read.
    pub fn from_pid(pid: u32) -> Result<Self> {
        let userns_path = format!("/proc/{}/ns/user", pid);
        let metadata = std::fs::metadata(&userns_path)
            .with_context(|| format!("Failed to stat {}", userns_path))?;

        use std::os::unix::fs::MetadataExt;
        let userns_id = metadata.ino();

        Ok(Self { pid, userns_id })
    }
}

/// Perform the namespace delegation: enter the target namespace, mount bpffs,
/// and return to the original context.
///
/// This is the core of the "nsenter dance". The caller must have
/// `CAP_SYS_ADMIN` (or equivalent) in the initial namespace.
///
/// # Arguments
///
/// * `target` — the namespace to delegate to
/// * `mount_path` — where to mount bpffs inside the target namespace
///   (typically `/sys/fs/bpf`)
/// * `opts` — which BPF operations to delegate (bitmaps)
///
/// # Errors
///
/// Returns an error if any `setns()` or `mount()` call fails. The function
/// always attempts to restore the original namespace context, even on error.
///
/// # Thread safety
///
/// This temporarily changes the calling thread's namespace context. It must
/// not be called concurrently with other namespace operations on the same
/// thread. In an async runtime, run this in a dedicated blocking thread.
pub fn delegate_bpf_to_namespace(
    target: &TargetNamespace,
    mount_path: &str,
    opts: &DelegationOpts,
) -> Result<()> {
    // Save our current namespace FDs so we can return
    let self_userns = open_ns_fd("self", "user")?;
    let self_mntns = open_ns_fd("self", "mnt")?;

    // Open target namespace FDs
    let target_userns = open_ns_fd(&target.pid.to_string(), "user")?;
    let target_mntns = open_ns_fd(&target.pid.to_string(), "mnt")?;

    // Enter target user namespace
    setns(&target_userns, CloneFlags::CLONE_NEWUSER)
        .context("Failed to enter target user namespace")?;

    // Enter target mount namespace
    setns(&target_mntns, CloneFlags::CLONE_NEWNS)
        .context("Failed to enter target mount namespace")?;

    // Mount bpffs with delegation options.
    // Because we're now in the target userns, s_user_ns will be set to
    // the target namespace, allowing token creation from within.
    let mount_data = opts.to_mount_data();
    let result = mount(
        Some("bpf"),
        mount_path,
        Some("bpf"),
        MsFlags::MS_NOSUID | MsFlags::MS_NODEV | MsFlags::MS_NOEXEC | MsFlags::MS_RELATIME,
        Some(mount_data.as_str()),
    )
    .context("Failed to mount bpffs in target namespace");

    // Always return to our original namespace, regardless of mount result
    let _ = setns(&self_userns, CloneFlags::CLONE_NEWUSER);
    let _ = setns(&self_mntns, CloneFlags::CLONE_NEWNS);

    result
}

/// Revoke BPF delegation by unmounting bpffs in the target namespace.
///
/// Enters the target namespace, calls `umount()`, and returns to the
/// original context. Existing BPF file descriptors held by processes in
/// the namespace remain valid, but no new tokens can be created.
pub fn revoke_bpf_delegation(target: &TargetNamespace, mount_path: &str) -> Result<()> {
    let self_userns = open_ns_fd("self", "user")?;
    let self_mntns = open_ns_fd("self", "mnt")?;

    let target_userns = open_ns_fd(&target.pid.to_string(), "user")?;
    let target_mntns = open_ns_fd(&target.pid.to_string(), "mnt")?;

    setns(&target_userns, CloneFlags::CLONE_NEWUSER)
        .context("Failed to enter target user namespace")?;
    setns(&target_mntns, CloneFlags::CLONE_NEWNS)
        .context("Failed to enter target mount namespace")?;

    let result = nix::mount::umount(mount_path).context("Failed to unmount bpffs");

    let _ = setns(&self_userns, CloneFlags::CLONE_NEWUSER);
    let _ = setns(&self_mntns, CloneFlags::CLONE_NEWNS);

    result
}

fn open_ns_fd(pid_or_self: &str, ns_type: &str) -> Result<File> {
    let path = format!("/proc/{}/ns/{}", pid_or_self, ns_type);
    OpenOptions::new()
        .read(true)
        .open(&path)
        .with_context(|| format!("Failed to open {}", path))
}

/// Check if the given path is a bpffs mount point by inspecting `/proc/mounts`.
pub fn is_bpffs_mounted(path: &Path) -> bool {
    if let Ok(contents) = std::fs::read_to_string("/proc/mounts") {
        contents.lines().any(|line| {
            let parts: Vec<&str> = line.split_whitespace().collect();
            parts.len() >= 3 && parts[1] == path.to_string_lossy() && parts[2] == "bpf"
        })
    } else {
        false
    }
}
